# Generated by Django 3.1 on 2022-01-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypwal', '0003_auto_20220126_0206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
