# Generated by Django 3.1 on 2022-01-25 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypwal', '0004_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletitem',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='walletitem',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
