# Generated by Django 4.0.2 on 2022-02-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypwal', '0005_auto_20220126_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='walletitem',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='walletitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
