# Generated by Django 4.0.2 on 2022-02-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypwal', '0006_walletitem_price_walletitem_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletitem',
            name='dayValue',
            field=models.FloatField(default=0),
        ),
    ]
