# Generated by Django 4.0.2 on 2022-02-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypwal', '0007_walletitem_dayvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletitem',
            name='dayValueChange',
            field=models.FloatField(default=0),
        ),
    ]
