# Generated by Django 3.1 on 2022-02-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypwal', '0008_walletitem_dayvaluechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
